site_name: Laravel Vault Suite
site_description: Pro-grade vault-backed secrets tooling for Laravel with multi-backend support.
site_url: https://omar-karray.github.io/laravel-vault-suite/
repo_url: https://github.com/omar-karray/laravel-vault-suite
repo_name: omar-karray/laravel-vault-suite
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - Operations:
      - Artisan Commands: commands.md
      - Configuration Reference: configuration.md
      - Programmatic API: api.md
  - Architecture: context.md
  - Integrations:
      - RawDigs Core App: integration/rawdigs-core-app.md
  - Deployment: deployment.md
  - Changelog: changelog.md
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - fenced_code
  - tables
plugins:
  - search
