name: Fix PHP code style issues

on:
  push:
    branches:
      - '**'
    paths:
      - '**.php'

permissions:
  contents: write

jobs:
  php-code-styling:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@2.6

      - name: Commit changes
        if: github.ref_type == 'branch'
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Fix styling
          branch: ${{ github.ref_name }}
